#!/bin/bash
# Claude Code 实战课程 - PDF生成指南

echo "📄 Claude Code 实战课程 - PDF生成指南"
echo "======================================"
echo ""

MD_FILE="/Users/lartemacfiles/Desktop/VPT-初诊数据/Claude_Code实战课程_完整版.md"
HTML_FILE="/Users/lartemacfiles/Desktop/VPT-初诊数据/Claude_Code实战课程_完整版.html"
PDF_FILE="/Users/lartemacfiles/Desktop/VPT-初诊数据/Claude_Code实战课程_完整版.pdf"

echo "✅ 文件准备完成！"
echo ""
echo "📁 生成的文件："
echo "   1. Markdown: $MD_FILE"
echo "   2. HTML: $HTML_FILE"
echo ""
echo "📋 PDF生成方案："
echo ""
echo "方案1: 使用浏览器打印（推荐，最简单）"
echo "-----------------------------------"
echo "1. 双击打开HTML文件："
echo "   $HTML_FILE"
echo ""
echo "2. 在浏览器中按 Cmd+P 打开打印对话框"
echo ""
echo "3. 在打印对话框中："
echo "   - 目标打印机选择: '保存为PDF' 或 'Microsoft Print to PDF'"
echo "   - 点击'打印'或'保存'"
echo ""
echo "方案2: 在线转换工具"
echo "-------------------"
echo "1. 访问在线转换网站："
echo "   https://www.markdowntopdf.com/"
echo "   或"
echo "   https://cloudconvert.com/md-to-pdf"
echo ""
echo "2. 上传Markdown文件: $MD_FILE"
echo ""
echo "3. 等待转换并下载PDF"
echo ""
echo "方案3: 安装专业工具"
echo "-------------------"
echo "如果需要自动化生成PDF，可以安装以下工具："
echo ""
echo "a) 安装Homebrew（如果未安装）："
echo "   /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo ""
echo "b) 安装pandoc："
echo "   brew install pandoc"
echo "   brew install --cask basictex"  # 用于PDF支持"
echo ""
echo "c) 使用pandoc生成PDF："
echo "   pandoc \"$MD_FILE\" -o \"$PDF_FILE\" --pdf-engine=xelatex -V CJKmainfont='PingFang SC'"
echo ""

# 尝试自动打开HTML文件
if [ -f "$HTML_FILE" ]; then
    echo "🚀 正在尝试自动打开HTML文件..."
    open "$HTML_FILE" 2>/dev/null && echo "✅ HTML文件已在浏览器中打开" || echo "⚠️  请手动打开HTML文件"
    echo ""
fi

echo "💡 提示："
echo "   - 浏览器打印生成的PDF质量最好"
echo "   - 可以在打印设置中调整页边距、页眉页脚等"
echo "   - 建议使用Chrome或Safari浏览器"
echo ""

